
# matrix:
  # include:
    # - language: python
      # python: 2.7
      # before_script:
      #   - cd backend/tests
      # script:
      #   - python -m unittest discover

    # - language: node_js
    #   node_js: "11"
    #   before_script:
    #     - npm install
    #   script:
    #     - npm run build

dist: xenial
language: node_js
node_js: "11"
python: "3.7"
install:
  - npm install
script:
  - npm run build

notifications:
  email:
    - sandro.bauer.93@gmail.com