language: python
dist: xenial
node_js: '11'
python: '3.7'
cache:
  directories:
    - node_modules
install:
  - npm install
jobs:
  include:
    - stage: unit test
      script:
        - make build
        - make test